AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Send me github user data
Resources:
  gitData:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: Send me github user data
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::<account_id>:role/<role_name>'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
      Environment:
        Variables:
          auth: >-
            <kms_encrypted_password>
          user: <gihub_user

# Note about role:
# My lambda role includes the following attached policies: AmazonSESFullAccess, AWSLambdaBasicExecutionRole, AWSKeyManagementServicePowerUser
# If you chose to implement a similar system it is a good practice to be as restrictive as possible when assigning roles
# These rols are a basd example of that
